function output_folder = demo_run_emsica(maxsteps, output_tag)
% demo_run_emsica() Run Extended EMSICA from the cached Infomax initializer.
%
% demo_run_emsica()                  % manuscript configuration, 100 steps
% demo_run_emsica(2, 'smoke')        % short installation test
%
% Author: Arthur C. Tsai
% Email: arthur@stat.sinica.edu.tw; arthurctsai@gmail.com
% Copyright (c) Extended EMSICA-PAC contributors
% SPDX-License-Identifier: BSD-3-Clause

if nargin < 1 || isempty(maxsteps), maxsteps = 100; end
if nargin < 2 || isempty(output_tag), output_tag = 'demo'; end
% 123456789012345678901234567890123456789012345678901234567890123456789012345678

setup_emsica_pac();
rng(0, 'twister');

simulation_run( ...
  recompute_synthX=0, ...
  recompute_B0=0, ...
  subjects={'zm09'}, ...
  B0method='infomax', ...
  maxsteps=maxsteps, ...
  myalpha=0.0125, ...
  mybeta=27.7, ...
  spatiotemporal_mix_ramp_steps=100, ...
  spatiotemporal_mix_exp_k=1, ...
  require_cached_B0=1, ...
  overwrite_guard=0, ...
  emsica_output_tag=output_tag, ...
  runemsica_log_suffix=output_tag, ...
  skip_accuracy_plot=1);

output_folder = fullfile(getenv('EMSICA_PAC_STUDY_ROOT'), 'zm09', '6emsica', ...
  ['ICs-synth-infomax-extended-' output_tag '-full']);
if maxsteps >= 4
  s = get_info('zm09');
  result_relative = ['6emsica/ICs-synth-infomax-extended-' output_tag '-full/'];
  plot_S_spect_and_mmi(s, [], [], result_relative, 1);
end
fprintf('Extended EMSICA result: %s\n', output_folder);
end
