% runemsica_by_sphx() This program is called by emsica_() or emsica_4raicar_() to run EMSICA model:
%
% --------------------------
% x_clean = Ltilde Btilde s
% --------------------------
% Input:
%   EEG0 is optional and usually set to be [] when calling by emsica_(), it will get it automatically in this program
%   but when calling with for loop, eg. in emsica_4raicar_() you had better feed it outside the for loop.
%   ref. emsica_4raicar_
%
% To get the concept, see
% o ~/media/emsica/emsica_wrapper.lyx 'x_clean = Ltilde Btilde s' section
% there are two kind of strategy:
%       shp == sph, in sph x_clean = sph LBs <-- this runemsic_by_sphx_source_space() use this (recommanded)
%       shp == WB,  in  WB x_clean = uB = WB LBs <-- another function runemsica_by_WBx() does this
% Output:
%   6emsica/ICs/B.mat
%   6emsica/ICs/zm01.set
%
% History: 
% Arthur Tsai 2004
% Frank Chang 2009
% Arthur
% 2010.07.17 major revision and clairification
% 2021-06-29 check thoroughly align with my updated ~/media/emsica/emsica_wrapper.lyx
% 2024-11-15 get SigmainvB0, invC, LSigma from EEG0 load by eg. 6emsica/B0/zm01.set 
% which is generated by get_LB0A0_by_sphx_source_space.m 
% Todo: edit the same thing for get_LB0A0_by_WBx.m
%
% Author: Arthur C. Tsai, Institute of Statistical Science, Academia Sinica, June 2026
% Copyright (c) 2026 Extended EMSICA-PAC contributors
% SPDX-License-Identifier: BSD-3-Clause

function EEG = runemsica_by_sphx(s, EEG0, varargin)
defaultsetting = {...
  ... % name       type       range  default
  'emsicafolder',  'string',  [],    '';... % '6emsica/gradient-cyto'
  'emsicatype',    'string',  [],    'gradient';... % gradient (recommanded) | fastemsica | bypass
  };

[g, s] = gparser(s, varargin, defaultsetting); ff = fieldnames(g);
for i = 1:length(ff), eval([ff{i} '=getfield(g,''' ff{i}  ''');']); end % flatten parameters

mymd(workingdir); cd(workingdir); 
% 123456789012345678901234567890123456789012345678901234567890123456789012345678

% extract ICsR01 from workingdir
strings = strsplit(s.workingdir, '/');
dirname = strings{end-1}; % Adjusted to ignore the empty string after final '/'

% Capture setup, training, and result saving in one run log.
ownsDiary = ~isfield(s, 'diaryfile') || isempty(s.diaryfile);
if ownsDiary
  diaryfile = [workingdir 'log-' mfilename '-' emsicatype '.txt'];
  myrm(diaryfile);
  diary(diaryfile);
  diaryCleanup = onCleanup(@() diary('off')); %#ok<NASGU>
else
  diaryfile = char(string(s.diaryfile));
end
s.diaryfile = diaryfile;
s.emsicatype = emsicatype;
mdisp(' ');
fprintf(['------------------------------------------------------------------\n' ...
  ' %s %s\n' ...
  '------------------------------------------------------------------\n'], ...
  [s.subject ' ' dirname ' :: ' mfilename() '() ::'], ...
  datestr(now, 'mmm dd, yyyy | HH:MM:SS'));

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% setup B0dir according to emsicatype
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% eg. workingdir = '~/1_zen/zm20/6emsica/gradient-lap-lh+rh-meshes/';
% replace 'gradient' with 'B0'
if ~strcmp(emsicatype, 'bypass')
  tmp = emsicatype;
end

if strcmp(emsicatype, 'bypass')
  switch true
    case contains(emsicafolder, 'B0')
      tmp = 'B0';
    case contains(emsicafolder, 'gradient')
      tmp = 'gradient';
    case contains(emsicafolder, 'fastemsica')
      tmp = 'fastemsica';
    otherwise
      tmp = 'gradient'; % default
      mdisp('yellow', ['Here for emsicatype == bypass, suppose you were using emsicatype == ' tmp]);
  end
end
B0dir = strrep(workingdir, tmp, 'B0'); % '~/1_zen/zm20/6emsica/B0-lap-lh+rh-meshes/';

 % 2025-01-10 tentatively always use ../B0-I/ for 1_zen study
if contains(emsicafolder, '/ICsR')
  % B0dir = [workingdir '../B0-' lapmethod '/']; % ../B0-I/
  B0dir = [workingdir '../B0-I/']; % always use ../B0-I/
end

% 2025-10-17 for simulation study
% Map folders like ICs-synth-all3off/ -> B0-synth-all3off/ so the
% inferred B0 path matches the B0set logic in emsica_().
if contains(emsicafolder, 'synth')
  [folderpath, foldername] = fileparts(emsicafolder(1:end-1)); % remove trailing '/'
  newfoldername = regexprep(foldername, '^[^-/]+', 'B0');
  B0dir = [s.subjectdir folderpath '/' newfoldername '/'];
end

% Prefer the explicitly requested synth B0 folder when available.
if isfield(s, 'emsica') && isstruct(s.emsica) && ...
    isfield(s.emsica, 'b0folder') && ~isempty(s.emsica.b0folder)
  explicitB0dir = char(string(s.emsica.b0folder));
  if ~endsWith(explicitB0dir, '/')
    explicitB0dir = [explicitB0dir '/'];
  end
  if ~startsWith(explicitB0dir, s.subjectdir)
    explicitB0dir = [s.subjectdir explicitB0dir];
  end
  B0dir = explicitB0dir;
elseif contains(emsicafolder, 'synth') && ...
    isfield(s, 'emsica') && isstruct(s.emsica) && ...
    isfield(s.emsica, 'simulation_run_args') && isstruct(s.emsica.simulation_run_args) && ...
    isfield(s.emsica.simulation_run_args, 'B0method') && ...
    ~isempty(s.emsica.simulation_run_args.B0method)
  synthB0method = char(string(s.emsica.simulation_run_args.B0method));
  switch lower(strtrim(synthB0method))
    case 'sloreta'
      synthB0method = 'sLORETA';
    case 'synthbs'
      synthB0method = 'synthBS';
  end
  [folderpath, ~] = fileparts(emsicafolder(1:end-1));
  B0dir = [s.subjectdir folderpath '/B0-synth-' synthB0method '/'];
end

% 2024-02-19 workaround for the case emsica_4raicar_()>runemsic_by_sphx_source_space()
if contains(workingdir, '/ICs/')
  B0dir = [workingdir '../B0/'];
end
mdisp('yellow', ['B0dir = ' B0dir]);

%% =====================================
%% get Xtilde by load EEG from 6emsica/B0/ as clean_x
%% =====================================
if isempty(EEG0)
  EEG = pop_loadset([B0dir s.dataset]);
else 
  EEG = EEG0;
end
% note you have saved:
% EEG.data = reshape(x_clean, I, EEG.pnts, EEG.trials); % x_clean
% in get_LB0A0_by_sphx_source_space.m
x_clean = double(reshape(EEG.data, [EEG.nbchan EEG.trials * EEG.pnts]));
sph = EEG.icasphere;
Xtilde=sph*x_clean;

%% =========================================
%% Create a surrogate dataset for Xtilde
%% =========================================
% Create a surrogate dataset by randomly sampling single time points from the original data.
% and adding noise in B0
% Note, in gradientemsica_() or gradientemsica_gpu() it always shuffles Xtilde
randmode = 1; % default
if isfield(s.emsica,'randmode')
  randmode = s.emsica.randmode;
end

if randmode,
  mdisp(['s.emsica.randmode = ' num2str(s.emsica.randmode) '. Create a surrogate dataset by randomly sampling single time points from the original data.']);
  [Xtilde, truth_resample_idx] = resample_data(Xtilde);
else
  mdisp(['s.emsica.randmode = ' num2str(s.emsica.randmode) '. No surrogate dataset, juse use original data.']);
  truth_resample_idx = [];
end


%% =========================================
%% get SigmainvB0, invC, LSigma from EEG0
%% =========================================

%% SigmainvB0
SigmainvB0 = EEG.SigmainvB0;
prescale = EEG.prescale;
[J, K] = size(SigmainvB0);

%% invC
invC = EEG.invC;
% keyboard
%% LSigma
% Note, in get_LB0A0_by_sphx_source_space() or get_LB0A0_by_WBx() we have done
% column normalization create LSigma by
% for j = 1 : size(L,2),
%   v = norm(L(:,j));
%   if abs(v) > 10 * eps
%     prescale.C(j) = 1/v;
%     L(:,j) = L(:,j) .* prescale.C(j);
%   end
% end
%
% Also, in get_LB0A0_by_sphx_source_space() we have done
% LSigma = LSigma(:,reorderIdx);
% LSigma(:,rmIndices) = [];
LSigma = EEG.LSigma;
sphinv = EEG.sphinv;
%% =============================================================================
%% calculate Ltilde
%% =============================================================================
% diary off
% % get rmIndices, reorderIdx
% [~, rmIndices, reorderIdx]=get_lap(s,'recompute','off', 'lapmethod',lapmethod);
% diary on
rmIndices = EEG.lap.rmIndices;
reorderIdx = EEG.lap.reorderIdx;
lapmethod = EEG.lap.lapmethod; 
s.lapmethod = lapmethod; % also save it to s, so we can print it in gradientemsica()
% Note, lapmethod determines Lap, and Lap determines invC. they are all calculated in get_LB0A0_by_sphx_source_space(), 
% so we save lapmethod in EEG.lap.lapmethod in get_LB0A0_by_sphx_source_space().
%
% As mentioned, the following procedures have been done in get_LB0A0_by_sphx_source_space() or get_LB0A0_by_WBx() 
% so i disable it. 2024-12-29 arthur
% LSigma = LSigma(:,reorderIdx);
% LSigma(:,rmIndices) = [];

% Here we explain Ltilde - 
% Note: we input gradientemsica()/fastemsica() with:
%        Xtilde = Ltilde Btilde
% and here Ltilde means that
%  Ltilde=sph*LSigma; for  sph x_clean = sph*LSigma Btilde s
%  Ltilde=WB*LSigma; for    WB x_clean = WB*LSigma Btilde s

Ltilde=sph*LSigma;

%% =============================================================================
%% run EMSICA ref. tsai 2006 neuroimage
%%  Xtilde, Ltilde, B0, invC -> Btilde
%% =============================================================================
% check if a GPU is available and whether the available GPU memory is greater than 2 GB:
if gpuDeviceCount >=1

  gpuInfo = gpuDevice;
  mdisp(['GPU detected: ', gpuInfo.Name]);

  % Check GPU memory (convert from bytes to GB)
  gpuMemoryGB = gpuInfo.AvailableMemory / (1024^3); % Convert bytes to GB
  totalMemoryGB = gpuInfo.TotalMemory / (1024^3);
  mdisp(['Before allocation gpuarray X, B0, etc, available GPU memory: ', num2str(gpuMemoryGB, '%.1f'), '/', num2str(totalMemoryGB, '%.1f') ' GB']);
  mdisp(['Also, in bash, you can use ''watch -n 1 nvidia-smi'' to monitor gpu memory usage.']);
  
  % Check if available memory > 1 GB
  if gpuMemoryGB > 1
    mdisp('GPU memory > 1 GB.');
    gpuflag = 1;
  else
    % GPU memory is less than or equal to 1 GB.');
    mdisp('GPU memory <= 1 GB.');
    gpuflag = 0;
  end
else
  mdisp('No GPU detected on this system.');
  gpuflag = 0;
end

%----! ----
% workaround 2024-11-13 arthur
% i tried using gpu inside parfor but failed
% so here just disable it
% gpuflag = 0;
%----! ----

% run_likelihood = 1;%0;
maxsteps=s.emsica.maxsteps;
% icatype   = s.emsica.icatype;

% calculate and save ./6emsica/gradient/SigmainvB.mat
if strcmp(emsicatype ,'gradient') || strcmp(emsicatype ,'fastemsica')
  tic
  if strcmp(emsicatype ,'gradient')
    if gpuflag >=1
      mdisp('This machine has gpu, so calling gradientemsica_gpu() to calculate B.');
      % 
      %   % Transfer data to GPU arrays at the beginning of each iteration
      %   X_gpu = gpuArray(single(X));      % Example: Convert X to single-precision GPU array
      %   L_gpu = gpuArray(single(L));      % Convert L to GPU array
      %   B0_gpu = gpuArray(single(B0));    % Convert B0 to GPU array
      %   invC_gpu = gpuArray(single(invC)); % Convert invC to GPU array
      %   imat_gpu = gpuArray(single(eye(K, K))); % Convert identity matrix to GPU array
      % 
      % The above is not good. Because, for invC, MATLAB's gpuArray function does not support converting sparse matrices 
      % to single precision directly. So to keep it as sparse, you need to move to GPU in double precision
      % Transfer data to GPU arrays at the beginning of each iteration
      X_gpu = gpuArray(Xtilde);      % Example: Convert X to single-precision GPU array
      L_gpu = gpuArray(Ltilde);      % Convert L to GPU array
      B0_gpu = gpuArray(SigmainvB0);    % Convert B0 to GPU array
      invC_gpu = gpuArray(invC); % Convert invC to GPU array
      imat_gpu = gpuArray(eye(K, K)); % Convert identity matrix to GPU array

      gpuInfo = gpuDevice;
      mdisp(['GPU detected: ', gpuInfo.Name]);

      % Check GPU memory (convert from bytes to GB)
      gpuMemoryGB = gpuInfo.AvailableMemory / (1024^3); % Convert bytes to GB
      mdisp(['After gpuarray allocation for X, L, B0, invC, etc. and before entering gradientemsica_gpu(), available GPU memory: ', num2str(gpuMemoryGB, '%.1f'), '/', num2str(totalMemoryGB, '%.1f') ' GB']);
 
      % Run your function with these GPU arrays as input
      extended = 1;
      % [w, a, Btilde, S] = gradientemsica_gpu(s, X_gpu, L_gpu, B0_gpu, invC_gpu, imat_gpu, extended);

      %% just for debuging See, http://emsica.art/synthb/eeg_2025_simulation#step_42_test2runica_exactly_inside_runemsica_by_sphx
      if 0
        % [w,sphere,meanvar,bias,signs,lrates,data,y] = runica(Xtilde, 'extended', 1, 'sphering', 'off', 'stop',1e-9, 'maxsteps',maxsteps);
        % a = pinv(w); % from gradientemsica_gpu()
        [w, sphere, meanvar, bias, signs, lrates, activations, a] = runica_a(Xtilde); %, 'extended', 1, 'sphering', 'off', 'stop',1e-9, 'maxsteps',maxsteps);

        U = w * Xtilde; % from gradientemsica_gpu()
        S = U;
        Btilde = SigmainvB0; % workaround
        mdisp
        disp(signs')
        %keyboard
      end

      if 1
        groundtruth = [];
        synth_truth_folder = '2epochs/EPs-synth/';
        if isfield(s, 'synth_truth_folder') && ~isempty(s.synth_truth_folder)
          synth_truth_folder = normalize_folder_local(s.synth_truth_folder);
        end
        synthTruthDir = [s.subjectdir synth_truth_folder]; %#ok<NASGU>
        synthTruth = load_synth_truth(s, truth_folder=synth_truth_folder, K=K);
        if contains(emsicafolder, 'synth') && ~isempty(synthTruth.B)
            Btruth = double(synthTruth.B);
            reorderTruthIdx = reorderIdx;
            reorderTruthIdx(rmIndices) = [];
            if size(Btruth, 1) == numel(reorderTruthIdx)
              % already reduced/reordered
            elseif size(Btruth, 1) >= max(reorderTruthIdx)
              Btruth = Btruth(reorderTruthIdx, :);
            else
              error('runemsica_by_sphx:GroundTruthBSize', ...
                'Ground-truth B rows (%d) do not match reduced (%d) or full reordered indexing (%d).', ...
                size(Btruth, 1), numel(reorderTruthIdx), max(reorderTruthIdx));
            end
            % Convert ground-truth B into the same Sigma^{-1}B / Btilde
            % parameterization used by EMSICA initialization.
            if isfield(prescale, 'C') && ~isempty(prescale.C)
              scaleC = double(prescale.C(:));
              Btruth = Btruth ./ scaleC;
            end
            groundtruth = struct();
            groundtruth.label = 'ground truth';
            groundtruth.B = Btruth;
            if ~isempty(synthTruth.Upreferred)
              groundtruth.U = synthTruth.Upreferred;
              if ~isempty(truth_resample_idx)
                groundtruth.U = groundtruth.U(:, truth_resample_idx);
              end
              mdisp('yellow', ['Loaded temporal target (' synthTruth.temporalSourceMode ') from ' synthTruth.setfile]);
            end
            mdisp('yellow', ['Loaded EMSICA target ground truth from ' synthTruth.bfile]);
        end
        [w, a, Btilde, S, bias, signs, meanvar] = gradientemsica_cpu_tidy(s, Xtilde, Ltilde, SigmainvB0, invC, eye(K,K), groundtruth);
        mdisp
        disp(signs')
      end

      % Clear GPU arrays explicitly at the end of each iteration to free memory
      clear X_gpu L_gpu B0_gpu invC_gpu imat_gpu;
      reset(gpuDevice);  % Reset the GPU device to free up memory

      % Optionally add a short pause to ensure memory is released
      pause(0.1);

      % After gradientemsica_gpu(), check GPU memory (convert from bytes to GB)
      gpuInfo = gpuDevice;
      gpuMemoryGB = gpuInfo.AvailableMemory / (1024^3); % Convert bytes to GB
      mdisp(['EMSICA training in ' workingdir ' is finished. After reset the GPU device, available GPU memory: ', num2str(gpuMemoryGB, '%.1f'), '/', num2str(totalMemoryGB, '%.1f') ' GB']);

    else
      mdisp(['This machine has no gpu, so calling gradientemsica() to calculate B.']);
      [w, a, Btilde, S] = gradientemsica(s, Xtilde, Ltilde, SigmainvB0, invC);
    end
    isConverged=1;
  end

  if strcmp(emsicatype ,'fastemsica')
    epsilon=1e-12;
    %keyboard;
    %[w sph]=runica(Xtilde,'sphering','off');
    %a=inv(w);
    %Btilde=B0;
    %S=w*Xtilde isConverged;
    mdisp(['calling fastemsica() to calculate B.']);
    [w, a, Btilde, S, isConverged] = fastemsica(s, Xtilde, Ltilde, SigmainvB0, invC, epsilon, maxsteps);
  end
  
  if maxsteps==0, % todo: see the figures in ICs whether it equal to B0 or not!
    a=eye(size(a)); w=a; S=Xtilde; Btilde = SigmainvB0;
    % 2011-10-29 and 2021-07-6 in this case maxsteps==0, it means we skip emsica learning
    % and keep the initialized B0 loaded above as the final Btilde.
    % to save B0.mat and it corresponding .set file for futher plot_as() plotting
    % if maxsteps==0, the 'a' matrix returned by gradientemsica or fastemsica() 
    % is very close to eye, here I force it to be eye
    % in order to observe icawinv=sphinv*a=sphinv on scalp map. 
    % which will be shown in eg. o06/6emsica/B0/
  end
  mytoc(toc);

  SigmainvB = Btilde;
  %   Bmat=[workingdir '../SigmainvB.mat'];
  %   save(Bmat,'SigmainvB','w','a', 'S');
  %   mdisp([Bmat ' is saved for plot_b() to plot B.']);
end % running gradientemsica()/fastemsica()


% A = LSigma*SigmainvB; % i.e., A = L * (Σ * Σ⁻¹) * B
% the above will be equivalent to
A = sphinv*a;





%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% for debugging, load previous saved SimginvB.mat
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% note here, the size of SigmainvB is the same as EEG.SigmainvB0
% which has removed some dipoles according EEG.lap.rmIndices
% it is smaller than B.mat
if ~strcmp(emsicatype ,'bypass')
  % save ./6emsica/gradient/SigmainvB.mat for further debugging purpose.
  Bmat=[workingdir 'SigmainvB.mat'];
  save(Bmat,'SigmainvB','w','a', 'emsicatype'); % S are not saved since it is not used
  mdisp([Bmat ' is saved for further debugging purpose.']);
  % keyboard;
end

if strcmp(emsicatype ,'bypass')
  Bmat=[workingdir 'SigmainvB.mat'];
  load(Bmat,'SigmainvB','w','a','emsicatype');
  mdisp([mypath(Bmat) ' is loaded for plot_b() to plot B.']);
end
% emsicatype, 'bypass': To test the following code
% to save time you can skip the above running gradientemsica()/fastemsica()
% and load previous saved ./6emsica/gradient/SigmainvB.mat

%%====================================================================
%% recover B from Sigma^-1 B
%%====================================================================
% Use Sigma*Btilde to recover B from Btilde.
% Note that Btilde == Sigma.^-1 * B
% i.e., Since we have applied column normalization to L,
% we have to recover the weight of Btilde.

% Note, the size of prescale.C and LSigma invC, SigmainvB0 are all appended to EEG by emsica_(s, ...B0..)
% and their size are smaller because they are removed by EEG.lap.rmIndices
for j = 1 : length(prescale.C) % 
  B(j,:) = prescale.C(j) .* SigmainvB(j,:);
end

%% ============================================================
%% fill the holes on SigmainvB0
%% ============================================================
returnBBonly=1; % don't plot just return SigmainvB0 only.
titlestr='';
B = fill_and_plot_bb(s, emsicafolder, B, rmIndices, reorderIdx, titlestr, returnBBonly);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% act --> z-score
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% In get_b() it will do
% [B,mu,sigma] = zscore(B.B);
% i.e., zscore just for plotting
% but here we save the true B.mat
% so the followings seem not necessary! -arthur 2021-07-21
% B=B0;
% for k=1:K,
%   B(:,k) = (B(:,k) - mean(B(:,k))) ./ std(B(:,k));
% end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% save B
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Bmat=[workingdir 'B.mat'];
save(Bmat,'B','w','a');
mdisp(['B, w, a is saved in ' Bmat ' for plot_b() to plot B.']);

% keyboard
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% save EEG .set for futhur plotting
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 2021-07-7 Note 
% 1. Since 
%    WB ~ sph in runemsica_by_sphx_source_space.m
%    AB ~ sphinv in runemsica_by_sphx_source_space.m 
%    Here we use sph from quasi-sphering
% 2. activation source, s, 
%    EEG.icaact = (EEG.icaweights*EEG.icasphere)*EEG.data;
%
%    s should be the same as what it really working in EMSICA
%                 s = w * Xtilde
%    the activation source:
%                 s = Wx 
%            icaact = (icaweights * icasphere) * data
%                 s = (w *           sph       ) * x_clean;
%     where w is returned by gradientemsica() w == pinv(a); a=Ltilde*Btilde;
%EEG=EEG(2);
EEG.icaweights = w; % KxK
EEG.icawinv = A; % == AB*a; % IxK
EEG.icasphere = sph; 
% Note: shp == WB in WB x_clean = uB = WB LBs 
%       shp == sph in sph x_clean = sph LBs

% EEG.icaact     = reshape(S, K, EEG.pnts, EEG.trials); % S
EEG.K=K; % number of EMSICA components
EEG.B = B;
EEG.emsicatype = emsicatype;

cd(workingdir);
pop_saveset(EEG, 'filename', s.dataset, 'filepath', workingdir);
mdisp([workingdir s.dataset ' is saved.']);
EEG = eeg_checkset(EEG);
% October 10, 2011 arthur: note that the function eeg_checkset.m will check
% EEG.icaact(:,tmpindices) = (EEG.icaweights*EEG.icasphere)*EEG.data(:,tmpindices);

% note:
% The eeg set eg. 1_hunt/h01/6emsica/h01.set is saved.
% When you plot ersp, you will split them to h01-press.set and h01-stop.set
% which don't have EEG.icaact inside.
% So when you load them (eg. when running icasso_.m)
% you get the signal
% ('eeg_checkset: recomputing the ICA activation matrix ...\n'); 
% then it will do
%           EEG.icaact = (EEG.icaweights*EEG.icasphere)*EEG.data;

% By the above setup, the EEG.icaact will be sucessfully maintained by
%                    s = w * WB * X 
%                      = w * WB * AB* uB
%                      = w * uB
% so it is maintained by s = w * uB which is working in gradientemsica()

% then, you can run:
% s='zm328';
% >> plot_as(s,'emsicafolder','emsica');
% >> plot_ersp_ongoingeeg3(s,'emsicafolder','emsica');

% keyboard;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% plot B
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% you can plot B, here, to see whether the rmIndices, reorderIdx,... ok or not
if 0
  figure;
  titlestr=['comp']; returnBBonly=0; 
  fill_and_plot_bb(s, emsicafolder, B, rmIndices, reorderIdx, titlestr,returnBBonly);
  %keyboard
end

if ownsDiary, diary off; end
return

% May 18, 2012 Arthur:
%  emsica_wrapper.m         get_b.m, get_bfeatures2.m                   plot_b3.m
% --------------------> B.mat --------------> h01.emsicab -----------> comp_xxxb.png

%% ==== Appendix ======
% 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % save EEG for futhur plotting
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %  Note:
% %    The activation source, s, 
% %    EEG.icaact = (EEG.icaweights*EEG.icasphere)*EEG.data;
% %
% %    s should be the same as what it really working in EMSICA
% %                 s = w * Xtilde
% %    the activation source:
% %                 s = Wx 
% %            icaact = (icaweights * icasphere) * data
% %                 s = (w *           sph       ) * x_clean;
% %     where w is returned by gradientemsica() w == pinv(a); a=Ltilde*Btilde;
% 
% % note in get_LB0A0_by_sphx_source_space.m Line:486
% % EEG.icawinv = sphinv*a; % IxK and
% % a==eye(K,K); % so
% sphinv = EEG.
% 
% I =length(icachansind2); % the size of x_clean used in ICA
% EEG.chanlocs = EEG.chanlocs(icachansind2);
% EEG.icachansind =  [1:I]; % since we are using x_clean, all channels are good
% EEG.nbchan = I;
% %
% 
% EEG.data = reshape(X, I, EEG.pnts, EEG.trials); % x_clean
% 
% 
% EEG.icaweights = w; % KxK
% EEG.icawinv = sphinv*a; % IxK
% EEG.icasphere = sph; % KxI
% 
% EEG.icaact = reshape(S, K, EEG.pnts, EEG.trials); % S
% EEG.K=K; % number of EMSICA components
% 
% cd(s.workingdir);
% pop_saveset(EEG, 'filename', s.dataset, 'filepath', s.emsicaDir);
% mdisp([mypath(s.emsicaDir) s.dataset ' is saved.']);
% EEG = eeg_checkset(EEG);
% % October 10, 2011 arthur: note that in eeg_checkset.m it will check
% % EEG.icaact(:,tmpindices) = (EEG.icaweights*EEG.icasphere)*EEG.data(:,tmpindices);
% 
% % note:
% % The eeg set eg. 1_hunt/h01/6emsica/h01.set is saved.
% % When you plot ersp, you will split them to h01-press.set and h01-stop.set
% % which don't have EEG.icaact inside.
% % So when you load them (eg. when running icasso_.m)
% % you get the signal
% % ('eeg_checkset: recomputing the ICA activation matrix ...\n'); 
% % then it will do
% %           EEG.icaact = (EEG.icaweights*EEG.icasphere)*EEG.data;
% 
% % By the above setup, the EEG.icaact will be sucessfully maintained by
% %                    s = (w * sph) * x_clean 
% %                      = w * Xtilde
% % so it is maintained by s = w * Xtilde which is working in gradientemsica()

%% ==== Appendix ======
%
%pop_topoplot(EEG,0, [1:8] , 'epoched pruned with ICA',[3 3] ,0, 'electrodes', 'on', 'masksurf', 'on');
%keyboard;

%plotting for debugging purpose
if 0,
  nbchan = EEG.nbchan;

  for i=1:10:nbchan
    n=i:min(i+10-1,nbchan);
    pop_topoplot(EEG,0, n , 'epoched',[4 3] ,0, 'electrodes', 'on', 'masksurf', 'on');
    print('-dpng',sprintf(['sphinv_%03d-%03d.png'],min(n),max(n)));
  end
end;


% this has become an independent function in misc/fill_and_plot_bb.m
% %% =============================================================================
% %% fill_and_plot_bb(), a sub function which calls plot_b() for debug
% %% =============================================================================
% % good! a very useful function. by arthur 2021-07-22
% function BBfilled = fill_and_plot_bb(s, BB, rmIndices, reorderIdx, titlestr,returnBBonly)
%   if nargin<=4
%     titlestr='comp'; % titlestr = eg. 'invL-sLORETA'
%   end
% 
%   if nargin<=5
%     returnBBonly=0;
%   end
% 
%   % BB should be a square matrix like B matrix
%   [JJ, KK] = size(BB); if JJ<KK, BB=BB'; end
% 
%   % zscore on BB
%   [BB,mu,sigma] = zscore(BB);
% 
%   %% ==============================================
%   %% the broken hole on BB is filled with zero
%   %% ==============================================
%   % -arthur 2021-07-27
%   [cortex, ~, combined] = get_dipoles(s, 'meshspace','both', 'reducemesh',1);
%   % Jc=length(cortex.mesh.vertices);% Jc, the index of cortex in B
%   J=length(combined.mesh.vertices);
% 
%   %  idx = combined.idx; idx_bak = idx;
%   %  BBfilled=[];
%   %   rmIndices = [idx; idx+1; idx+2; idx+3; idx+4];
%   %   for i=1:length(combined.idx)
%   %     idx(2:end) = idx(2:end)-5;
%   %     partidx=idx(1,:);
%   %     idx(1,:)=[];
%   %     BBpart=[zeros(5,K); BB(partidx(1):partidx(2),:)];
%   %     BBfilled=[BBfilled; BBpart];
%   %   end
%   %   BB=BBfilled;
% 
%   if JJ==J, BBfilled = BB; end;
% 
% 
%   if JJ<J
%     % rkffabcd 2021-09-3 
%     BBfilled = zeros(J,KK);
%     %keyboard
%     reorderIdx(rmIndices) = [];
%     
%     % [~,idx] = sort(reorderIdx);
%     % >> reorderIdx = [3 7 5]; 
%     % >> [a,idx]=sort(X)
%     % ans: a =
%     %     3     5     7
%     % idx =
%     %     1     3     2
% 
%     BBfilled(reorderIdx,:)=BB;
%   end
% 
%   % not to plot by bb, just return BB for eg. SigmainvB0
%   if returnBBonly, return; end
% 
%   % to plot b, you can open the following segment for 
%   % cortical and subcortical part from BBfilled
%   if 0,
%     cortexB = BBfilled(1:Jc,:);
%     %cortexB(cortex.idxnongraymatter,:) = 0; 
%     subcorticalB = BBfilled(Jc+1:end,:);
% 
%     % keyboard
% 
%     BBB.B = cortexB;
%     BBB.Bl = get_allb(s,'lh', cortexB, []);
%     BBB.Br = get_allb(s,'rh', cortexB, []);
%     BBB.deepB=subcorticalB;
% 
%     % plot by plot_b() by passing s.B to it
%     s.B = BBB;
%     % plot_b(s, 'emsicafolder','B0', 'index', [1,10,20], 'titlestr', titlestr,'visible','on');
%     plot_b(s, 'emsicafolder','emsica', 'titlestr', titlestr,'visible','off'); % plot all components
% 
%     % set background to original to prevent further plotting color problem
%     whitebg([1 1 1]);
%   end
