% get_similarity() Usage 1: eg. myraicar(), pairing_(), pairing_eoey() > get_similarity()
%
% get_similarity()
% Usage 1: eg. myraicar(), pairing_(), pairing_eoey() > get_similarity()
% subjects={'zm01', 'zm018'}
%   [similarity, sk]=get_similarity(subjects, 'emsicafolder', 'ica', 'features',{'topo', 'spec'}, 'weightings',[.8, .2], 'K', K);
%
% Usage 2: eg. emsica_(s,...'B0',...) > sortcomps() > get_similarity()
%    You have asigned ALLEEG(1) and ALLEEG(2) to get similarity of eg. topo67x67 of these two EEG
%    In emscia_(2,...'B0',...) will call:
%   sortcomps('zm02', [], 'emsicafolder', '6emsica/ICsR01-I/', 'features',{'topo67x67'}, 'method','3ica/ICs/');
%   this will call:
%   [similarity, index]=get_similarity([],'EEG',ALLEEG, 'features', features,'recompute','on');
%
% Usage 3: eg. pairing3('zm01', 'emsicafolder', '6emsica/ICsR01-I/') > get_similarity({'zm01','zm018'},'s1k',[1 2 3 4 5]);
%   where s1k = [1 2 3 4 5] comes from ~/1_zen/7raicar/6emsica/ICsR01-I/clusters.txt
%   Note, s1k is the selected componets of zm01 after graicar_() component clustering
%   so s1k help us to restrict the component of zm01 when selecting paired components
% 
% History:
% 2014-07-31 rkffabcd
% 2025-01-03 rearrange arthur
%
% Author: Arthur C. Tsai, Institute of Statistical Science, Academia Sinica, June 2026
% Copyright (c) 2026 Extended EMSICA-PAC contributors
% SPDX-License-Identifier: BSD-3-Clause

function [similarity, sk]=get_similarity(subjects, varargin)
defaultsetting = {...
    % name         type      range   default
    'features',    'cell',   '',     {'topomi','topo67x67','spec','topo11'};...% topo67x67, topo11, spec, b...
    'weightings',  'real',   '',     [.5 .4 .1 .0];...
    'emsicafolder','string', '',     'ica';...
    'msg',         'string', '',     'on';... % message {'on'} | 'off'
    'recompute',   'string', '',     'off';... %
    's1k',         'real',   '',     [];... % this is exclusive for pairing3() see Usage 3:
    'EEG',         'struct', '',     struct();...
    'skselected',  'real',   '',    [];... % default is empty
    % skselected is exclusively for demo of clustering_by_raicar4() clustering procedure
    % It cames from clusters.txt but reduce the number of components for better visualization
    % ref.   http://emsica.art/clustering/clustering_by_raicar#plot_figures_to_explain_the_clustering_procedure_of_raicar
    };

  if isempty(subjects) % eg. sortcomps()>get_similarity([], 'EEG', ALLEEG,...)
    % for sortcomps, eg. 6emsica/B0-I/ will be sorted according to 3ica/ICs/,
    % so these two EEG will be asigned in ALLEEG
    [g, s] = gparser([],varargin, defaultsetting); ff = fieldnames(g);
    S = length(g.EEG);
    subjects = {g.EEG.subject};
  else  % for eg. pairing3() > get_similarity(subjects)
    [g, s] = gparser(subjects{1},varargin, defaultsetting); ff = fieldnames(g);
    S = length(subjects);
  end

% flatten your parameters by extracting all fields in g
for i = 1:length(ff), eval([ff{i} '=getfield(g,''' ff{i}  ''');']); end % flatten parameters
    
allowed_features = {'topomi','topo67x67','spec','topo11','b','bmat'};
if any(~ismember(features, allowed_features))
  mdisp('red', ['sortcomps(): unsupported feature(s): ' mat2str(features)]);
  keyboard
end
% 123456789012345678901234567890123456789012345678901234567890123456789012345678

sk = [];
tic

%% get sk by EEGs for the case eg. sortcomps()>get_similarity([], 'EEG', ALLEEG,...)
% for sortcomps, eg. 6emsica/B0-I/ will be sorted according to 3ica/ICs/,
% so these two EEG will be asigned in ALLEEG
if isempty(subjects) 
  for i = 1:S
    K = size(EEG(i).icawinv, 2);
    sktmp = [i*ones(K,1) (1:K)'];
    sk = [sk;sktmp];
  end
end

%% get sk by EEGs for the case mygraicar_() for demo of RAICAR clustering procedure
if ~isempty(skselected)
  sk = skselected;
end

% normailize
weightings = weightings(1:length(features));
weightings = weightings/norm(weightings);

%% get sk by idx_manually.txt for the case of eg. mygraicar_(), pairing3() > get_similarity(subjects)
if isempty(EEG)
keyboard

  % subject 1
  stmp = get_info(subjects{1});
  EEG = pop_loadset([stmp.subjectdir emsicafolder stmp.dataset]);
  EEG.subject = subjects{1};

  % subject 2
  for i = 2:S
  stmp = get_info(subjects{i});
  EEGtmp = pop_loadset([stmp.subjectdir emsicafolder stmp.dataset]);
  EEGtmp.subject = subjects{i};
  
  %---- begin appending EEG(2) - check and try to automatically ignore inconsistent fields
  % code segment generated by chatgpt
% Automatically handle inconsistent fields
    if ~isequal(fieldnames(EEG), fieldnames(EEGtmp))
        fields1 = fieldnames(EEG);
        fields2 = fieldnames(EEGtmp);
        
        % Find inconsistent fields
        inconsistentFields = union(setdiff(fields1, fields2), setdiff(fields2, fields1));
        
        % Display a warning about the inconsistent fields
        disp(['Warning: Ignoring inconsistent fields: ', strjoin(inconsistentFields, ', ')]);
        
        % Remove inconsistent fields from both structures
        for f = 1:length(inconsistentFields)
            if isfield(EEG, inconsistentFields{f})
                EEG = rmfield(EEG, inconsistentFields{f});
            end
            if isfield(EEGtmp, inconsistentFields{f})
                EEGtmp = rmfield(EEGtmp, inconsistentFields{f});
            end
        end
    end
    % Now, you can safely assign EEGtmp to EEG here
    EEG(i) = EEGtmp;
  end % for i = 2:S
  %---- end of appending EEG(2)
end

if isempty(skselected)
  for i = 1:S
    stmp = get_info(subjects{i});
    % to ask get_similarity() use ICsR101/B.mat 2022-10-24 arthur
    stmp.workingdir = [EEG(i).filepath filesep];

    num_size = length(subjects);

    % Q: what this num_size is for? 2025-01-3 athur
    if num_size==1 && exist([stmp.studydir '7raicar/' stmp.emsicafolder '/pairing_' stmp.subject '.txt'],'file')
      txtfilename = [stmp.studydir '7raicar/' stmp.emsicafolder '/pairing_' stmp.subject '.txt'];
      mdisp('red', ['here, num_size==1, do you mean S==1, when will you go here? check it and add comments to explain here!!']);
      keyboard
    elseif exist([stmp.workingdir 'idx_manually.txt'],'file')
      txtfilename = [stmp.workingdir 'idx_manually.txt'];
    elseif exist([stmp.workingdir 'idx.txt'],'file')
      txtfilename = [stmp.workingdir 'idx.txt'];
    else
      disp(['Cannot find idx.txt and idx_manually.txt in ' stmp.workingdir]);
      disp([mfilename ': generate one!']);

      txtfilename = [stmp.workingdir 'idx.txt'];
      K = size(EEG(i).icawinv, 2);
      fid = fopen(txtfilename, 'w');
      for k=1:K
        fprintf(fid,'%d %d \n',1,k);
      end
      fclose(fid);
      mdisp(['*** a dummy idx.txt is generated in ' stmp.workingdir])

    end
    % mdisp(['reading ' txtfilename]);
    [list ,~] = read_num_in_file(txtfilename);

    % for the case of 
    % Usage 3: eg. pairing3('zm01', 'emsicafolder', '6emsica/ICsR01-I/') > get_similarity({'zm01','zm018'},'s1k',[1 2 3 4 5]);
    % i.e., filter list based on s1k
    if i==1 && ~isempty(s1k)
      % Keep only rows in list that have components matching s1k
      list = list(ismember(list(:,2), s1k), :);

      % Check for inconsistencies between list flags and components in s1k
      for k = 1:size(list, 2)
        if list(1, k) == 0 && ismember(k, s1k)
          error(['Error: Component ', num2str(k), ' is in s1k but has a flag of 0 in the list.']);
        end
      end
    end

    %        if num_size == 1 % for components clustering, remove artifact component lists
    rmidx = list(:,1)==0;
    list(rmidx,:) = [];
    %        end
    % Kmax is for demo of clustering_by_raicar4(). to reduce number of components for better visualization
    % this is old method, now we use skselected.
    % ref.       http://emsica.art/clustering/clustering_by_raicar#clustering_by_raicar3

    %  if ~isempty(Kmax)
    %    rmidx = list(:,2) >Kmax;
    %    list(rmidx,:) = [];
    %  end

    sktmp = [i*ones(length(list),1) sort(list(:,2))];
    sk = [sk;sktmp]; % sk of useful componets
  end
end

subject_numbers = sk(:,1); % Extract the first column (subject numbers)

% Find unique subjects and count occurrences
[unique_subjects, ~, idx] = unique(subject_numbers);
component_counts = accumarray(idx, 1);

% Loop through the unique subjects and display the component counts using disp
% % Display the results
% % Subject 1 has 70 components.
% % Subject 2 has 48 components.
% % Subject 3 has 21 components.
mdisp(' ');
for i = 1:length(unique_subjects)
    sbj = EEG(i).subject;
    filepath = EEG(i).filepath;
    mdisp(['Subject ' num2str(unique_subjects(i)), ' ' sbj ' in ' filepath '/ has ' num2str(component_counts(i)) ' components.']);
end

% now, you have got EEG(1), EEG(2), and sk

%% get similarity matrix
for i = 1:length(features)
    switch lower(features{i})
        case 'topoemd' %% topoemd 2025-02-5 arthur
            count = 0;
            for subj = 1:S
                KK = size(EEG(subj).icaweights,1);
                % to ask get_similarity() to use ICsR101/B.mat 2022-10-24 arthur
                % stmp = get_info(subjects{subj},emsicafolder);
                % stmp = get_info(subjects{subj});
                [stmp, emsicafolder] = eegfilepath2emsicafolder(EEG(subj).filepath);
                topotmp = get_topo(stmp, EEG(subj), 'K',KK, 'rmartifact','off', 'msg',msg, 'emsicafolder',emsicafolder, 'ffeature', 'topo67x67');
                comps = sk(sk(:,1)==subj,2);
                topo(count+1:count+length(comps),:,:)=topotmp(comps,:,:);
                count=count+length(comps);
            end
            % figure;imagesc(squeeze(topo(153,:,:)))

            mdisp('calculating topo Earth Mover’s Distance (EMD) ...');
            topoemd = zeros(size(topo,1));
            
            for j=1:size(topo,1)
                for k = (j+1):size(topo,1)
                    A1 = topo(j,:,:);
                    A2 = topo(k,:,:);

                    % A1(isnan(A1))=[]; % this may cause different length, so replace by the follows -athur 2024-10-25
                    % A2(isnan(A2))=[];

                    % Remove NaN values (if any)
                    validIdx = ~isnan(A1) & ~isnan(A2);
                    A1 = A1(validIdx);
                    A2 = A2(validIdx);

                    % emd_value = calculate_emd(A1, A2)
% emd_value = sum(abs(cumsum(A1) - cumsum(A2)));
% emd_value = pdist2(A1(:)', A2', 'cityblock');


% EEG topographies are often sign-invariant due to the nature of ICA decomposition or other spatial filters. 
% A topographic map and its inverted version (i.e., multiplied by -1) can represent the same underlying neural component.
% To make the Earth Mover’s Distance (EMD) measure sign-invariant, 
% you can compute EMD for both the original and flipped topographies, then take the minimum:
% Note, For two vectors A1 and A2, you should reshape them into row vectors before passing them to pdist2()
% 2025-02-5 arthur
emd_value_orig = pdist2(A1', A2', 'cityblock');  % Original EMD 
emd_value_flipped = pdist2(A1', -A2', 'cityblock'); % Flipped EMD

emd_value = min(emd_value_orig, emd_value_flipped); % Choose the minimum
                    % Display Normalized Mutual Information
                    % mdisp(['emd between the two topographies: ', num2str(emd_value)]);

                    % Store NMI in the matrix
                    topoemd(j,k) = emd_value;
                    topoemd(k,j) = emd_value;
                end
            end
            max_emd = max(topoemd(:)); % Get the maximum EMD directly from the matrix
            topoemd = 1 - (topoemd / max_emd); % Transform to similarity (0 to 1)

            % Ensure values are strictly within 0-1 range
            %topomi = max(0, min(1, topomi));

            % keyboard

        case 'topomi' %% topomi
            count = 0;
            for subj = 1:S
                KK = size(EEG(subj).icaweights,1);
                % to ask get_similarity() to use ICsR101/B.mat 2022-10-24 arthur
                % stmp = get_info(subjects{subj},emsicafolder);
                % stmp = get_info(subjects{subj});
                [stmp, emsicafolder] = eegfilepath2emsicafolder(EEG(subj).filepath);
                topotmp = get_topo(stmp, EEG(subj), 'K',KK, 'rmartifact','off', 'msg',msg, 'emsicafolder',emsicafolder, 'ffeature', 'topo67x67');
                comps = sk(sk(:,1)==subj,2);
                topo(count+1:count+length(comps),:,:)=topotmp(comps,:,:);
                count=count+length(comps);
            end
            % figure;imagesc(squeeze(topo(153,:,:)))

            mdisp('calculating topoplot Normalized Mutual Information (NMI) ...');
            topomi = zeros(size(topo,1));
            
            for j=1:size(topo,1)
                for k = (j+1):size(topo,1)
                    A1 = topo(j,:,:);
                    A2 = topo(k,:,:);

                    % A1(isnan(A1))=[]; % this may cause different length, so replace by the follows -athur 2024-10-25
                    % A2(isnan(A2))=[];

                    % Remove NaN values (if any)
                    validIdx = ~isnan(A1) & ~isnan(A2);
                    A1 = A1(validIdx);
                    A2 = A2(validIdx);

                    % Assume A1 and A2 are the topographies of two ICs you want to compare
                    % Discretization example (simple binning here, consider more sophisticated approaches for real data)
                    %                     num_bins = 10; % Example number of bins
                    % num_bins =
                    % keyboard;
                    A1_discrete = discretize(A1, 16)';
                    A2_discrete = discretize(A2, 16)';

                    if 0 % the result is strange so I disable it and replace with the following suggested by chatgpt 2025-02-5 arhtur
                      % Calculate mutual information
                      [MI] = calcNMI(A1_discrete, A2_discrete, 1, 16);

                      % Display the mutual information
                      % mdisp(['Normalized Mutual Information (NMI) between the two topographies: ', num2str(MI)]);
                      % the value usually between 0 to 1
                      % 2025-02-5 MI obtained by calNMN() looks not always between 0-1
                      % keyboard 
                      topomi(j,k) = MI;
                      topomi(k,j) = MI;
                    end % the result is strange so I replace with the following suggested by chatgpt 2025-02-5 arhtur

                    % Calculate probability distributions 2025-02-5
                    [P1, ~] = histcounts(A1_discrete, 16, 'Normalization', 'probability');
                    [P2, ~] = histcounts(A2_discrete, 16, 'Normalization', 'probability');

                    % Compute joint probability distribution
                    bin_edges = linspace(min([A1_discrete, A2_discrete]), max([A1_discrete, A2_discrete]), 17); % 16 bins need 17 edges
                    jointHist = histcounts2(A1_discrete, A2_discrete, bin_edges, bin_edges, 'Normalization', 'probability');

                    % Compute entropy values
                    H1 = -sum(P1 .* log2(P1 + eps));
                    H2 = -sum(P2 .* log2(P2 + eps));
                    H_joint = -sum(jointHist(:) .* log2(jointHist(:) + eps));

                    % Compute Mutual Information (MI)
                    MI = H1 + H2 - H_joint;

                    % Normalize MI (NMI) to ensure it remains between 0 and 1
                    NMI = MI / max(H1, H2);

                    % Display Normalized Mutual Information
                    mdisp(['Normalized Mutual Information (NMI) between the two topographies: ', num2str(NMI)]);

                    % Store NMI in the matrix
                    topomi(j,k) = NMI;
                    topomi(k,j) = NMI;

                end
            end
            % keyboard
      case 'topo67x67' %% topo67x67
        count = 0;
        for subj = 1:S
                KK = size(EEG(subj).icaweights,1);

                [stmp, emsicafolder] = eegfilepath2emsicafolder(EEG(subj).filepath);
                topotmp=get_topo(stmp, EEG(subj), 'K',KK, 'rmartifact','off', 'msg',msg, 'emsicafolder',emsicafolder, 'ffeature', features{i});
                comps = sk(sk(:,1)==subj,2);
                topo(count+1:count+length(comps),:,:)=topotmp(comps,:,:);
                count=count+length(comps);
            end
            % figure;imagesc(squeeze(topo(153,:,:)))

            mdisp('calculating topoplot correlation...');
            topocorr = zeros(size(topo,1));
            for j=1:size(topo,1)
              for k = (j+1):size(topo,1)
                A1 = topo(j,:,:);
                A2 = topo(k,:,:);

                % Remove NaN values (if any)
                validIdx = ~isnan(A1) & ~isnan(A2);
                A1 = A1(validIdx);
                A2 = A2(validIdx);

                % Compute correlation for both the original and sign-flipped versions to handle topographical sign ambiguity.
                % arthur 2025-02-5
                r_orig = corrcoef(A1, A2);  % Original correlation
                r_flipped = corrcoef(A1, -A2); % Flipped correlation

                % Extract absolute correlation values
                r_orig = abs(r_orig(1,2));  
                r_flipped = abs(r_flipped(1,2));

                % Choose the maximum correlation (ignoring sign flips)
                r = max(r_orig, r_flipped); % <----------------
                % Check for NaN and handle it
                if isnan(r)
                  topocorr(j,k) = 0;
                  topocorr(k,j) = 0;
                else
                  topocorr(j,k) = r;
                  topocorr(k,j) = r; % r(1,2) equals r(2,1)
                end
              end % for k
            end % for j

        case 'spec' %% spec
            specs = [];
            for subj = 1:S
                KK = size(EEG(subj).icaweights,1);
                [stmp, emsicafolder] = eegfilepath2emsicafolder(EEG(subj).filepath);
                [spectmp] = get_spec(stmp, EEG(subj), 'K',KK, 'rmartifact','off', 'emsicafolder',emsicafolder, 'msg',msg, 'recompute',recompute);
                %keyboard
                comps = sk(sk(:,1)==subj,2);
                specs(end+1:end+length(comps),:,:)=spectmp(comps,:,:);
            end
            mdisp('Calculating Spec correlation!');
            speccorr = zeros(size(specs,1));
            for j=1:size(specs,1)
                for k = (j+1):size(specs,1)
                    r=corrcoef(specs(j,:,:),specs(k,:,:));
                    r=abs(r);
                    speccorr(j,k) = r(1,2);
                    speccorr(k,j) = r(1,2);
                end
            end

        case 'topo11' % 11 scalp regions
            topo11s = [];
            for subj = 1:S
                KK = size(EEG(subj).icaweights,1);
                [stmp, emsicafolder] = eegfilepath2emsicafolder(EEG(subj).filepath);
                topo11tmp = get_topo(stmp, EEG(subj), 'K',KK, 'rmartifact','off', 'msg',msg, 'emsicafolder',emsicafolder, 'ffeature', features{i});
                comps = sk(sk(:,1)==subj,2);
                topo11s(end+1:end+length(comps),:)=topo11tmp(comps,:);
            end
            mdisp('Calculating Topo11 correlation!');
            tp11corr = zeros(size(topo11s,1));
            for j=1:size(topo11s,1)
                for k = (j+1):size(topo11s,1)
                    r=corrcoef(topo11s(j,:,:),topo11s(k,:,:));
                    r = abs(r);
                    rvalue = r(1,2);

                    % Check if value is NaN
                    if isnan(rvalue)
                        tp11corr(j,k) = 0;
                        tp11corr(k,j) = 0;
                    else
                        tp11corr(j,k) = rvalue;
                        tp11corr(k,j) = rvalue;
                    end
                end
            end
        case {'b' 'bmat'} %% active source area on the cortical surface
            % to ask get_similarity() use ICsR101/B.mat 2022-10-24 arthur
            % 2025-01-19 arthur improve this segment by using icasig


            switch lower(features{i})
                case 'b'
                    matname = 'ICsR_1.mat';
                case 'bmat'
                    matname = 'B.mat';
            end

            allBB=[];
            for subj=1:S
                % [stmp, emsicafolder] = eegfilepath2emsicafolder(EEG(subj).filepath);
                stmp=subjects{subj};
                stmp = get_info(stmp);
                
                icasigfile= [g.EEG(subj).filepath filesep matname ];
                % note: icasig is saved in emsica_4raicar_sortcomps_as_ersp_b_()
                % icasigfile= [stmp.subjectdir emsicafolder matname ];
                mdisp(['loading ' icasigfile]);
                BB = load(icasigfile);
                comps = sk(sk(:,1)==subj,2);
                ff = fieldnames(BB);
                %icasig = abs(BB.icasig(comps,:));
                if strcmp(matname,'B.mat')
                    icasig = BB.B(:,comps)';
                else
                    icasig = BB.icasig(comps,:);
                end
                allBB = [allBB; icasig];  % 12*37(only flag==1 components) x 84 note: number of subject==12
            end

            % % use distance()
            % allBcorr = distance(allBB',allBB'); %12*45 x 12*45
            % mm = max(allBcorr(:));
            % allBcorr= (mm-allBcorr)/mm; % rescale to 0~1

            % test using corrw() to speedup % 2022-06-11  -arthur
            % use corrw()
            % m = size(allBB, 2);
            % allBcorr = corrw(allBB, eye(m)); % row-wise corr

            % use corrcoef()
            allBcorr = corrcoef(allBB');
            allBcorr = abs(allBcorr);
            %keyboard

            % % compare corrw() and corrcoef() -act
            % B1=[ 1 2 3]; B2=[ 1 2 2.1];
            % BBall = [B1; B2]
            % m = size(BBall, 2);
            % allBcorr = corrw(BBall, eye(m)); % row-wise corr
            % %     1.0000    0.9845
            % %     0.9845    1.0000
            %
            % corrcoef(BBall'); % collumn-wise corr
            % %     1.0000    0.9042
            % %     0.9042    1.0000

            if 0
                for k = (j+1):size(allBcorr,1)
                    r=corrcoef(B1,B2);
                    r=abs(r);

                    %                     % consider:
                    %                     % >> corr([1 2 nan 3 4]',[1 2 3 nan nan]','rows','complete') % ans = 1.0000
                    %                     % >> corr([1 2 nan 3 4]',[2 1 3 nan nan]','rows','complete') % ans = -1.0000

                    %                     idx = and(B1<s.emsica.activationThreshold,...
                    %                         B2<s.emsica.activationThreshold);
                    %                     r=corrcoef(B1(idx),B2(idx));
                    %                     r=abs(r);

                    allBcorr(j,k) = r(1,2);
                    allBcorr(k,j) = r(1,2);
                    %
                    %                     figure; stem(B1,'color','r');hold on;stem(B2,'color','b');legend({[s1 ' k' k1];[s2 ' K' k2]})
                    %                     for ii = find(B1>s.emsica.activationThreshold)'
                    %                         text(ii,B1(ii),['L' num2str(ii)],'color','r','rotation',90)
                    %                     end
                    %                     for ii = find(B2>s.emsica.activationThreshold)'
                    %                         text(ii,B2(ii),['L' num2str(ii)],'color','b','rotation',90)
                    %                     end
                    %                     plot([0 length(B1)+1],s.emsica.activationThreshold*[1 1], 'Color', [0.8 0.8 0.8])

                end

                if isnan(r(1,2))
                    keyboard;
                end
            end
            % figure;imagesc(allBcorr); title('get_similarity: B corr');

        case 'beta'
            % copied from divisive.m
            cd(s.workingdir);

            allbeta = [];
            for s = 1:S
                try
                    filename = [s.studydir filesep subjects{s} '/3ica/ICs/gift_temporal_regression.csv'];
                    fS = csvread(filename,1,1)'; % (8x45)'
                catch
                    fS=rand(s.nPCA,8);
                    disp(['cannot find ' mypath(filename)]);
                    keyboard
                end
                comps = sk(sk(:,1)==s,2);
                allbeta(end+1:end+length(comps),:)=fS(comps,:);
            end
            betacorr = zeros(size(allbeta,1));
            for j=1:size(allbeta,1)
                for k = 1:size(allbeta,1)
                    r=corrcoef(allbeta(j,:),allbeta(k,:));
                    r=abs(r);
                    betacorr(j,k) = r(1,2);
                end
            end
            figure;imagesc(betacorr);title('Beta corr');
    end % switch features{i}

end
%% weighting
similarity = zeros(length(sk));

for i = 1:length(features)
    switch lower(features{i})
        case 'topomi'
            similarity = weightings(i)*topomi+similarity;
        case 'topoemd'
            similarity = weightings(i)*topoemd+similarity;
        case 'topo67x67'
            similarity = weightings(i)*topocorr+similarity;
        case 'spec'
            similarity = weightings(i)*speccorr+similarity;
        case 'topo11'
            similarity = weightings(i)*tp11corr+similarity;
        case 'beta'
            similarity = weightings(i)*betacorr+similarity;
        case {'b','bmat'}
            similarity = weightings(i)*allBcorr+similarity;
    end
    if any(any(isnan(similarity)))
        mdisp(features{i})
        keyboard;
    end
end
mdisp(['This program overall took ' mytoc(toc)]);
end

