% verify_demo() Validate packaged data or run a short EMSICA test.
%
% Author: Arthur C. Tsai, Institute of Statistical Science, Academia Sinica, June 2026
% Copyright (c) 2026 Extended EMSICA-PAC contributors
% SPDX-License-Identifier: BSD-3-Clause

function verify_demo(level)
% 123456789012345678901234567890123456789012345678901234567890123456789012345678

if nargin < 1 || isempty(level), level = 'data'; end
cfg = setup_emsica_pac();

required = { ...
  fullfile(cfg.subject_dir,'2epochs','EPs-synth','zm09.set'), ...
  fullfile(cfg.subject_dir,'2epochs','EPs-synth','zm09.fdt'), ...
  fullfile(cfg.subject_dir,'2epochs','EPs-synth','B.mat'), ...
  fullfile(cfg.subject_dir,'2epochs','EPs-synth','mmitmp.mat'), ...
  fullfile(cfg.subject_dir,'3ica','ICs-synth-infomax','zm09.set'), ...
  fullfile(cfg.subject_dir,'3ica','ICs-synth-infomax','zm09.fdt'), ...
  fullfile(cfg.subject_dir,'3ica','ICs-synth-infomax','B.mat'), ...
  fullfile(cfg.subject_dir,'3ica','ICs-synth-infomax','mmitmp.mat'), ...
  fullfile(cfg.subject_dir,'5lfm','source_plot_geometry.mat'), ...
  fullfile(cfg.subject_dir,'6emsica','B0-synth-infomax','zm09.set'), ...
  fullfile(cfg.subject_dir,'6emsica','B0-synth-infomax','zm09.fdt')};
missing = required(~cellfun(@isfile, required));
assert(isempty(missing), 'Missing packaged demo file: %s', strjoin(missing, ', '));
assert(isempty(dir(fullfile(cfg.subject_dir, '**', 'idx.txt'))), ...
  'Packaged demodata should not contain generated idx.txt caches.');
assert(isempty(dir(fullfile(cfg.subject_dir, '**', 'EEG_topo67x67.mat'))), ...
  'Packaged demodata should not contain topology caches.');

switch lower(string(level))
  case "data"
    fprintf('Immutable demo-data validation passed.\n');
  case "smoke"
    folder = demo_run_emsica(2, 'smoke');
    assert(isfile(fullfile(folder, 'zm09.set')), ...
      'Smoke EEGLAB result was not created.');
    expected = fullfile(cfg.result_root, ...
      'ICs-synth-infomax-extended-smoke-full');
    assert(strcmp(folder, expected), ...
      'Smoke result was not written to the structured output folder.');
    assert(isfile(fullfile(folder, ...
      'log-runemsica_by_sphx-gradient.txt')), ...
      'Unified EMSICA run log was not created.');
    assert(~isfile(fullfile(folder, 'log.txt')), ...
      'Redundant legacy log.txt was created.');
    assert(~isfile(fullfile(folder, 'runemsica.log')), ...
      'Obsolete runemsica.log was created.');
    assert(~startsWith(folder, cfg.subject_dir), ...
      'Generated output must not be written under demodata.');
    fprintf('EMSICA smoke validation passed.\n');
  otherwise
    error('verify_demo:UnknownLevel', 'Level must be data or smoke.');
end
end
