% get_dipoles_subcortical() This function is called by get_dipoles(), idx_idv2avg(), runbem(), lfm_().
%
% This function is called by get_dipoles(), idx_idv2avg(), runbem(), lfm_()
% get_dipoles() > get_dipoles_cortical(), get_dipoles_subcortical()
%
% get_dipoles_subcortical()
% Input:
%   For subject with MRI, the input of this function is subcorticalmeshes from get_subcorticalmeshs(s)
%   For subject without MRI, the input is dipoles_subcortical_reduced_warped.mat from get_dipoles_warping_5layers(s)
%   but it stored warped reduced mesh only, to get unwarped unreduced mesh we call subcorticalmeshes = get_subcorticalmeshes(s)
%
% Output:
%   1. mesh: reduced subcortical mesh (12 meshed have been combined to 1 mesh)
%   2. subcortical diples
%   3. dipmatfile file name
%   4. mesh_subcortical_dec: for subject without MRI, mesh_subcortical_dec is obtained from MNI_20131226_updated.mat which contains original template subcorticals before warping
% Note:
%  1. dipoles = [mesh.vertices/1000 vertNormalsUnit];
%     2024-05-11
%     For fMRI, usually reducemesh ='off', we will have dipoles_subcortical.mat only
%     For EEG with MRI subject, we need dipoles_subcortical_reduced.mat for leadfield calculation and also dipoles_subcortical.mat for plot_l(), plot_b() > get_allbmeshcurv()
%
%  2. Now we use outer_skin_surface instead of mri_scalp
%
% See http://emsica.art/cortical/get_dipoles_subcortical#output -arthur 2023-04-27
% See also: get_subcorticalmeshes, get_dipoles_cortical
%
% 2021-06-13, 2023-04-15 reorganize -arthur
% 2023-04-27 use outer_skin_surface, show legend -arthur
% 2024-08-14 plotmoree on by rkffabcd & arthur
%
% Author: Arthur C. Tsai, Institute of Statistical Science, Academia Sinica, June 2026
% Copyright (c) 2026 Extended EMSICA-PAC contributors
% SPDX-License-Identifier: BSD-3-Clause

function [mesh, dipoles, dipmatfile, mesh_subcortical_dec] = get_dipoles_subcortical(s, varargin)
  s = get_info(s);
  defaultsetting = {...
    %  name       type       range default
    'reducemesh', 'integer', [],   s.reducemesh ;... % 'on' | 'off'
    'recompute',  'string',  [],   'off' ;... % 'on' | 'off'
    'logging',    'string',  [],   'off';...
    'plotmore',   'real',    [],   0;... % 0 | 1
    };

[g, s] = gparser(s, varargin, defaultsetting); ff = fieldnames(g);
for i = 1:length(ff), eval([ff{i} '=getfield(g,''' ff{i}  ''');']); end % flatten parameters

mymd(s.lfmDir); cd(s.lfmDir);
if strcmp(logging,'on')
  logfid = fopen([s.lfmDir 'L/log.txt'],'a');
else
  logfid=[];
end
mesh_subcortical_dec = []; % default
alreadyreduced = 0;
% 123456789012345678901234567890123456789012345678901234567890123456789012345678

%% ============ (1) For subjects without MRI using warping method ============
if ~hasmri(s) && ~contains(s.subject,'7raicar')
  if ~reducemesh 
    cdisp('red', ['For EEG without MRI subject, we have only dipoles_subcortical_reduced_warp.mat from get_dipoles_warping_5layers(),']);
    cdisp('red', ['There is no un-reduced, i.e., full, meshes inside.']);
    error([mfilename '(): ERROR!']);
  end

  %dipmatfile = 'dipoles_subcortical_reduced_warped.mat'; % for subject without mri, always use this file generated by get_dipoles_warping_5layers()
  % Replace '.mat' with '_warped.mat' in the filename
  % strrep(dipmatfile, '.mat', '_warped.mat'); % dipoles_subcortical_reduced_warped.mat
  %if exist(dipmatfile,'file')
  %  recompute = 0;
  %  mdisp(['...loading ' mypath(dipmatfile)]);
  %else
  %  hasmri(s,1); % to show message: 'The subject 'zm10' has no mri
  %  mdisp(['Cannot find ' dipmatfile '. Running get_dipoles_warping_5layers(''' s.subject ''') to get ' dipmatfile '.'])
  %get_dipoles_warping_5layers(s);

  % 2024-10-28 to be finished below
  [mesh, dipoles, ~, dipmatfile, mesh_subcortical_dec] = get_dipoles_warping_5layers(s, 'toget','subcortical');
  %end
  %  load(dipmatfile,'vertNormals', 'vertNormalsUnit', 'smoothsubcorticalreducedmesh', 'mesh_subcortical_dec');
  %  dipoles = [smoothsubcorticalreducedmesh.vertices/1000 vertNormalsUnit];
  % note see get_dipoles_warping_5layers(), smoothsubcorticalreducedmesh is subcortical mesh after warping
  % mesh_subcortical_dec is subcortical mesh before warping
  % in the following we assign original segmentLabel and verticesIdx to the warped mesh
  smoothsubcorticalreducedmesh = mesh;
  mesh.segmentLabel = mesh_subcortical_dec.segmentLabel;
  mesh.verticesIdx= mesh_subcortical_dec.verticesIdx;

%% ===== (2) The following is similar to subcortical_reducepatch() but… ======
% 2024-09-21 rkffabcd
  subcortical_reduced.vertices=[];
  subcortical_reduced.faces=[];
  subcortical_reduced.segmentLabel={};
  subcortical_reduced.FieldLabel={};
  subcortical_reduced.segmentFaces=[];
  subcortical_reduced.segmentVertices=[];
  subcortical_reduced.verticesIdx=[]; % [start end] of each label

  fidx = 1;
  % FieldLabel

  for ii = 1:length(mesh_subcortical_dec.segmentLabel)
    segmentLabel = mesh_subcortical_dec.segmentLabel{ii};
    iidx = mesh_subcortical_dec.verticesIdx(ii,1) : mesh_subcortical_dec.verticesIdx(ii,2);
    tmpDec.vertices = mesh_subcortical_dec.vertices(iidx,:);
    tmpDec.faces = mesh_subcortical_dec.faces(fidx:fidx+mesh_subcortical_dec.segmentFaces(ii)-1,:)-mesh_subcortical_dec.verticesIdx(ii,1)+1;

    %         tmpDec = reducepatch(tmpDec,1);

    % Here is to generate mesh.lThalamus, lCaudate,.... which is crucial for get_lap()
    switch (segmentLabel)
      %case % 'lh.Thalamus'
      case 'Left-Thalamus-Proper'
        subcortical_reduced.lThalamus=tmpDec;
        FieldLabel = 'lThalamus';
      case 'Left-Caudate'  
        subcortical_reduced.lCaudate=tmpDec;
        FieldLabel = 'lCaudate';
      case 'Left-Putamen' 
        subcortical_reduced.lPutamen=tmpDec;
        FieldLabel = 'lPutamen';
      case 'Left-Pallidum'  
        subcortical_reduced.lPallidum=tmpDec;
        FieldLabel = 'lPallidum';
      case'Left-Hippocampus' 
        subcortical_reduced.lHippocampus=tmpDec;
        FieldLabel = 'lHippocampus';
      case 'Left-Amygdala' 
        subcortical_reduced.lAmygdala=tmpDec;
        FieldLabel = 'lAmygdala';
        %case % 'lh.Insula'
        %case % 'rh.Thalamus'
      case 'Right-Thalamus-Proper'
        subcortical_reduced.rThalamus=tmpDec;
        FieldLabel = 'rThalamus';
      case 'Right-Caudate'
        subcortical_reduced.rCaudate=tmpDec;
        FieldLabel = 'rCaudate';
      case 'Right-Putamen'
        subcortical_reduced.rPutamen=tmpDec;
        FieldLabel = 'rPutamen';
      case 'Right-Pallidum'
        subcortical_reduced.rPallidum=tmpDec;
        FieldLabel = 'rPallidum';
      case 'Right-Hippocampus'
        subcortical_reduced.rHippocampus=tmpDec;
        FieldLabel = 'rHippocampus';
      case 'Right-Amygdala' 
        subcortical_reduced.rAmygdala=tmpDec;
        FieldLabel = 'rAmygdala';
        %case %'rh.Insula'
    end %% case

    subcortical_reduced.faces=[subcortical_reduced.faces ; tmpDec.faces+length(subcortical_reduced.vertices)];
    subcortical_reduced.vertices=[subcortical_reduced.vertices ;mesh_subcortical_dec.vertices(iidx,:)];        
    subcortical_reduced.segmentFaces=[subcortical_reduced.segmentFaces ; size(tmpDec.faces,1)];
    subcortical_reduced.segmentVertices=[subcortical_reduced.segmentVertices ; size(tmpDec.vertices,1)];
    subcortical_reduced.segmentLabel=[subcortical_reduced.segmentLabel ; segmentLabel];
    subcortical_reduced.FieldLabel=[subcortical_reduced.FieldLabel ; FieldLabel];
    subcortical_reduced.verticesIdx=[subcortical_reduced.verticesIdx; fidx  fidx+mesh_subcortical_dec.segmentFaces(ii)-1];

    fidx = fidx+mesh_subcortical_dec.segmentFaces(ii);
  end
  mesh = subcortical_reduced;


end % if subject has no mri

%% ======================== (3) For subjects with MRI ========================
if hasmri(s)
  if ~reducemesh % call by get_allbmeshcurv()
    dipmatfile = [s.lfmDir 'dipoles_subcortical.mat'];
  else % usually, 
    dipmatfile = [s.lfmDir 'dipoles_subcortical_reduced.mat'];
  end
  if ~exist(dipmatfile)
    recompute=1;
  end

  portable_cached = ~isempty(getenv('EMSICA_PAC_ROOT')) && isfile(dipmatfile);
  if portable_cached
    recompute = 0;
  else
    recompute = checkrecompute(recompute, dipmatfile, [s.surfDir 'lh.Thalamus-Proper.smooth.asc']); % if dipmatfile is newer than surf/lh.Thalamus-Proper.smooth.asc, good, recompute=0
  end
%keyboard % check why it kept recomputing all the time 2024-11-26 arthur

  if ~recompute % just load .mat
    mdisp(['...loading ' mypath(dipmatfile)]);
    load(dipmatfile); %,'vertNormals', 'vertNormalsUnit', 'mesh');

    % workaround for 2esspfmriyear1 study 2024-05-11
    if exist('subcortical_dipoles','var')
      mesh = subcortical_dipoles;
    end

    % [vertNormals, vertNormalsUnit] = mesh_vertex_normals(mesh);
    dipoles = [mesh.vertices/1000 vertNormalsUnit];
  end
end % if subject has mri

%% ======================= (4) Plot subcortical meshes =======================
if plotmore
  if ~hasmri(s)
    % for subject without mri
    % note that here 'subcorticalmeshes' is from .colin27 which is not what we used for leadfield calculation
    % what we used for leadfield calculation is smoothsubcorticalreducedmesh
    % so, here we put the warped meshes, smoothsubcorticalreducedmesh, into subcorticalmeshes for plotting and observation 2024-05-15
    re = cell(1,5);
    re{1} = 1;
    re{2} = 'all';
    re{3} = [122 186 220 0]; % use color [0 118 14 0];
    re{4} = smoothsubcorticalreducedmesh.vertices;
    re{5} = smoothsubcorticalreducedmesh.faces;
    vis; mydraw(s,'scalp-subcortical',re,0); % without scalp
    vis; mydraw(s,'scalp-subcortical',re,1); % with scalp
  end

  if hasmri(s)
    if ~exist('subcorticalmeshes','var')
      subcorticalmeshes = get_subcorticalmeshes(s);
    end

    vis; mydraw(s,'scalp-subcortical',subcorticalmeshes,0); % without scalp
    vis; mydraw(s,'scalp-subcortical',subcorticalmeshes,1); % with scalp
  end
end

%% ================== (5) Check the length of mesh.vertices ==================
if exist('mesh','var')
  alreadyreduced = (length(mesh.vertices)/10000 < 1);
  if and(alreadyreduced , reducemesh) 
    return;
  end

  if and(~alreadyreduced , ~reducemesh) 
    return;
  end
end

%% ====== (6) For subject with MRI recompute dipoles_subcortical.mat /… ======
  subcorticalmeshes = get_subcorticalmeshes(s);

  if reducemesh
    mesh = subcortical_reducepatch(subcorticalmeshes, 0.1); % reduce rate =0.1
  else % for fMRI, usually reducemesh ='off'
    mesh = subcortical_reducepatch(subcorticalmeshes, 1);
  end



  mtic=tic;
  [vertNormals, vertNormalsUnit] = mesh_vertex_normals(mesh);
  mdisp(['mesh_vertex_normals() took ' mytoc(toc(mtic))]);

  % ~/1_zen/zm32/5lfm/lfm_subcortical.dip
  dipoles = [mesh.vertices/1000 vertNormalsUnit];

if hasmri(s) && recompute
  logprintf(logfid,'\n-------------------------------\n %s %s\n------------------------------\n',['::' mfilename() ':'],[s.subject ', ' datestr(now, 'mmm dd, yyyy | HH:MM:SS')]);
  mdisp(['making ' dipmatfile ' ...']);

  % ~/1_zen/zm32/5lfm/dipoles_subcortical.mat
  save(dipmatfile,'vertNormals', 'vertNormalsUnit', 'mesh');
  mdisp([mypath(dipmatfile) ' saved.']);

end % if subject has mri && recompute

% Note that, now, we donot save
% lfm_corticals.dip and 
% lfm_subcorticalmeshes.dip anymore.
% The reason is that they (dipoles) can be accessed by calling
% [mesh, dipoles] = get_dipoles_cortical() and get_dipoles_subcortical(), respectively.
% So the following codes are useless now. 2024-04-14 -arthur

% save(dipfile, 'dipoles', '-ascii');
% mdisp([mypath(dipfile) ' saved.']);


  function mydraw(s,name,subcorticalmeshes,flag)
    ;
%% ====================== (7) For subjects without MRI =======================
    if hasmri(s)
      % use outer_skin_surface instead of mri_scalp -arthur 2023-04-27
      % read watershed outer_skin_surface
      mdisp('loading watershed/_outer_skin_surface...');
      [vertices, faces ]= freesurfer_read_surf([s.lfmDir 'watershed/_outer_skin_surface']);
    end

    if ~hasmri(s)
      mdisp('nonewline','... loading lfm_warp/outerskin.mat saved by get_dipoles_warping_5layers()');
      load([s.lfmDir '/lfm_warp/outerskin.mat']);
      disp('done.');
      % if faied, run get_dipoles_warping_5layers for MNI
      % keyboard
      faces = Escalp(:,2:4);
      vertices=Cscalp_w(:,2:4);
    end

    figure('Name',name); vis
    for i=1:5
      subplot(2,3,i);
      if flag
        plotmesh_color(faces, vertices, [], 1, 'none', [1,.75,.65], 0.5);% transparent plot
        %plotmesh_color(faces, vertices, [], 1,[1,.75,.65], 'none',1);
        hold on
      end
      plotmesh_color2(subcorticalmeshes,[], 1);

      switch i
        case 1
          view(90,0); %title('view(90,0)');
        case 2
          view(180,0); %title('view(180,0)');
        case 3
          view(270,0); %title('view(270,0)');
        case 4
          view(180,-90); %title('view(180,-90)');
          title('inferior')
        case 5
          view(180, 90); %title('view(180,-90)'); % superior
          title('superior')
      end

      puttext();

    end % for i=1:5


%% ====== (8) Add legend for each subcortical region -arthur 2023-04-27 ======
    if i==5
      n=size(subcorticalmeshes,1)/2;
      n = ceil(n);
      region_names = cell(n,1); % preallocate region_names cell array
      region_colors = zeros(n,3); % preallocate region_colors matrix

      for i=1:n
        split_name = strsplit(subcorticalmeshes{i,2}, '.');
        region_names{i} = split_name{end};
        region_colors(i,:) = subcorticalmeshes{i,3}(1:3)/256;
      end

      % Add legend
      region_patches = zeros(length(region_names), 1);
      for i = 1:length(region_names)
        region_patches(i) = patch('DisplayName', region_names{i}, 'FaceColor', region_colors(i,:), 'EdgeColor', 'none');
      end
      ll = legend(region_patches);
      set(ll,'position',[0.7697 0.2626 0.1113 0.0413]); % 
    end

    % ~/1_zen/zm32/5lfm/subcorticalmeshes0.png
    pngfilename = mypath([s.lfmDir 'subcorticalmeshes' int2str(flag) '.png']);
    print('-dpng',pngfilename);  % close;
    mdisp([pngfilename ' is printed.']);



    function puttext()
      tmp=get(gca,'Xlim');
      l=tmp(1);
      r=tmp(2);
      tmp=get(gca,'Ylim');
      p=tmp(1);
      a=tmp(2);
      tmp=get(gca,'Zlim');
      s=tmp(2);
      z0=(tmp(1)+tmp(2))/2;

      text(0,0,0.9*s,'S');
      text(1.1*r,0,z0,'R');
      text(1.1*l,0,z0,'L');
      text(0,1.1*a,z0,'A');
      text(0,1.1*p,z0,'P');
      axis equal;


      %{

      % 2024-05-11
      % some codes for further reference:
      % mape 
      % subcorticalmeshes={ 'lh.Thalamus',... 
      % with
      % mesh_subcortical_dec.segmentLabel, 
      % with label like Left-Thalamus
      %
      %
      %
      %
      s = s.subcorticalmeshes; % stored in get_info.m as followings
      % pick up part of $FREESURFER_HOME/FreeSurferColorLUT.txt
      %               No.   Label name                             R  G  B  A
      % subcorticalmeshes={ 
      %               % 9  , 'lh.Thalamus',                        [0   118 14  0] %
      %                 10 , 'lh.Thalamus-Proper',                 [0   118 14  0]
      %                 11 , 'lh.Caudate' ,                        [ 122 186 220 0]
      %                 12 , 'lh.Putamen' ,                        [ 236 13  176 0]
      %                 13 , 'lh.Pallidum' ,                       [ 12  48  255 0]
      %                 17 , 'lh.Hippocampus' ,                    [ 220 216 20  0]
      %                 18 , 'lh.Amygdala'  ,                      [ 103 255 255 0]
      %               % 19 , 'lh.Insula'     ,                     [ 80  196 98 0]  %
      %               % 48 , 'rh.Thalamus'  ,                     [ 0   118 14 0]  %
      %                 49 , 'rh.Thalamus-Proper',                [ 0   118 14 0]
      %                 50 , 'rh.Caudate'   ,                     [ 122 186 220 0]
      %                 51 , 'rh.Putamen'   ,                     [ 236 13  176 0]
      %                 52 , 'rh.Pallidum'   ,                    [ 13  48  255 0]
      %                 53 , 'rh.Hippocampus' ,                   [ 220 216 20  0]
      %                 54 , 'rh.Amygdala'   ,                    [ 103 255 255 0]
      %               % 55 , 'rh.Insula'  ,                      [ 80  196 98 0] %
      %                 };

      % get subcortical surface

      % Iterate through each entry in the subcorticalmeshes
      for i = 1:size(subcorticalmeshes, 1)
      % Print the structure name
      disp(['s.subcorticalmeshes segment name: ' subcorticalmeshes{i, 2}]);
      % Convert 'lh.' and 'rh.' to 'Left-' and 'Right-' for matching
      modifiedName = strrep(subcorticalmeshes{i, 2}, 'lh.', 'Left-');
      modifiedName = strrep(modifiedName, 'rh.', 'Right-');

      % Find the corresponding index in mesh_subcortical_dec.segmentLabel
      idx = find(strcmp(mesh_subcortical_dec.segmentLabel, modifiedName));

      % Check if a corresponding name was found
      if ~isempty(idx)
      % Print the corresponding segment label
      disp(['Corresponding segment name in mesh_subcortical_dec: ' mesh_subcortical_dec.segmentLabel{idx}]);
      keyboard

      subcorticalmeshes{i,4}=vertices(:,1:3);
      subcorticalmeshes{i,5}=faces(:,1:3);

    else
      fprintf('No corresponding segment found for %s\n', modifiedName);
    end
  end
  keyboard

  %}
